Version 2.3.12
git-svn-id: https://libqglviewer.googlecode.com/svn/trunk@175 da6d9524-6789-53b3-a77f-85cae9118ae5

diff --git a/examples/makeDist b/examples/makeDist
--- a/examples/makeDist
+++ b/examples/makeDist
@@ -93,7 +93,7 @@ done
 
 test -d $OUTPUT_DIR || mkdir -p $OUTPUT_DIR
 
-which "source-highlight" >& /dev/null || error "Unable to find source-highlight - Abort"
+#which "source-highlight" >& /dev/null || error "Unable to find source-highlight - Abort"
     
 export LC_TIME="en"
 date=`date "+%A, %B %d, %Y"`
@@ -206,24 +206,19 @@ do
     done
     fileList="$fileList $file"
   done
-  
 
   for file in $fileList
     do
     echo "<h2>$(echo $file | sed s#$name/##)</h2>" >> $output
-    source-highlight -s cpp -f html -i $file >> $output
-    #cat $tmp/src-high.html >> $output
-    #echo "<pre>" >> $output
-    #sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g' $tmp/src-high >> $output
-    #echo "</pre>" >> $output
+    #source-highlight -s cpp -f html -i $file >> $output
+    echo "<pre>" >> $output
+    sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g' $file >> $output
+    echo "</pre>" >> $output
     echo -e "\n" >> $output
   done
 
   writeFooter
 done
-
-
-
 
 
 # Create the contrib examples HTML files with simple description
diff --git a/makeDist b/makeDist
--- a/makeDist
+++ b/makeDist
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 libName="libQGLViewer"
-version="2.3.10"
+version="2.3.12"
 
 WebURL="http://www.libqglviewer.com"
 
@@ -18,8 +18,8 @@ allTarGZ="$libNameVersion-all.tar.gz"
 
 cd $QGLViewerRootDir
 
-DOS2UNIX="dos2unix -o -p -q"
-UNIX2DOS="unix2dos -o -q"
+DOS2UNIX="" #"dos2unix -o -q"
+UNIX2DOS="" #"unix2dos -o -q"
 
 # echo "$0 disabled for security"
 # exit
@@ -80,6 +80,7 @@ function checkGrep()
   grep "$TARGET" $FILE > /dev/null
   if [[ "$?" -ne "0" ]]
   then
+	echo
     echo "ERROR : $TARGET not found in $FILE"
     exit 1
   fi
@@ -90,6 +91,7 @@ function checkVersion()
   grep "^$START$VERSION" $FILE > /dev/null
   if [[ "$?" -ne "0" ]]
   then
+	echo
     echo "Version found in $FILE is not $VERSION - Patching"
     sed s~"^$START.*"~"$START$VERSION"~ $FILE > /tmp/makeDist
     cp /tmp/makeDist $FILE
@@ -173,15 +175,17 @@ checkVersion
 echo -n " files"
 
 # Convert possible Windows encoding
-find . -type f -a \( -name '*.cpp' -o -name '*.h' -o -name '*.ui' -o -name '*.html' -o -name '*.txt' -o -name '*.pro' -o -name '*.pri' -o -name '*.ui' -o -name '*.ago' -o -name '*.css' -o -name '*.bwb' \) -exec $DOS2UNIX {} \; > /tmp/error 2>&1 
-grep -v "/\.svn/" /tmp/error
-if [[ "$?" -eq "0" ]]
+if [[ $DOS2UNIX ]]
 then
-  echo "Error while converting newlines, see /tmp/error"
-  grep -v "/\.svn/" /tmp/error
-  exit 1
+	find . -type f -a \( -name '*.cpp' -o -name '*.h' -o -name '*.ui' -o -name '*.html' -o -name '*.txt' -o -name '*.pro' -o -name '*.pri' -o -name '*.ui' -o -name '*.ago' -o -name '*.css' -o -name '*.bwb' \) -exec $DOS2UNIX {} \; > /tmp/error 2>&1 
+	grep -v "/\.svn/" /tmp/error
+	if [[ "$?" -eq "0" ]]
+	then
+	  echo "Error while converting newlines, see /tmp/error"
+	  grep -v "/\.svn/" /tmp/error
+	  exit 1
+	fi
 fi
-
 
 TARGET="Gilles Debunne <contact@libQGLViewer.com> $version"
 FILE="QGLViewer/qglviewer.spec"
@@ -246,8 +250,11 @@ test -d $tmpDir || mkdir -p $tmpDir
 
 
 SOURCES="CHANGELOG INSTALL README LICENCE GPL_EXCEPTION gpl-warning libQGLViewer.pro"
-$DOS2UNIX $SOURCES &> /tmp/error
-test -s /tmp/error && more /tmp/error && error "Error while converting newlines to Unix"
+if [[ $DOS2UNIX ]]
+then
+	$DOS2UNIX $SOURCES &> /tmp/error
+	test -s /tmp/error && more /tmp/error && error "Error while converting newlines to Unix"
+fi
 TARGET=""
 makeDist
 
@@ -385,11 +392,12 @@ mv "libQGLViewer.pro" "$libNameVersion.pro"
 echo -n "sources"
 cd QGLViewer
 
-lupdate QGLViewer.pro 2> /dev/null
+lupdate QGLViewer.pro 2> /dev/null > /dev/null
 lrelease QGLViewer.pro 2> /dev/null > /tmp/lrelease
 
 if [ `grep "0 unfinished" /tmp/lrelease | wc -l` != 1 ]
 then
+  echo
   echo "Untranslated QString exist - Aborting"
   exit
 fi
@@ -449,7 +457,10 @@ rm gpl-warning
 vRenderCopyright="$QGLViewerRootDir/QGLViewer/VRender/copyright"
 test -f $vRenderCopyright || error "No copyright in VRender"
 
-$DOS2UNIX $vRenderCopyright
+if [[ $DOS2UNIX ]]
+then
+	$DOS2UNIX $vRenderCopyright
+fi
 
 for f in `find QGLViewer/VRender -name '*.h' -o -name '*.cpp'`
 do
@@ -492,7 +503,6 @@ do
   rm -r $f
   mv $newName-bis $newName
 done
-
 
 # Changing hierarchy page
 sed s%"This inheritance.*alphabetically:"%% hierarchy.html > /tmp/hierarchy.html
@@ -545,7 +555,7 @@ do
 done
 
 # Creating assistant qch file
-awk '/<section title="Namespace List"/ { skip=1 } /<\/toc>/ { print"      </section>"; skip=0 } { if (skip==0) print }' index.qhp > index.filtered.qhp
+awk '/<section title="Files"/ { skip=1 } /<\/toc>/ { print"      </section>"; skip=0 } { if (skip==0) print }' index.qhp > index.filtered.qhp
 qhelpgenerator index.filtered.qhp -o ../libQGLViewer-$version.qch > /dev/null
 rm index.qhp index.filtered.qhp
 
@@ -629,9 +639,11 @@ addNamespace ManipulatedCameraFrame ManipulatedFrame manipulatedCameraFrame
 #  cp $vcproj $target
 #done
 
-find . -type f -a \( -name '*.cpp' -o -name '*.h' -o -name '*.ui' -o -name '*.html' -o -name '*.txt' -o -name '*.pro' -o -name '*.pri' -o -name '*.ui' -o -name '*.ago' -o -name '*.css' -o -name '*.bwb' -o -name '*.vcproj' \) -exec $UNIX2DOS {} \; &> /tmp/error
-
-test -s /tmp/error && more /tmp/error && error "Error while converting newlines to DOS"
+if [[ $UNIX2DOS ]]
+then
+	find . -type f -a \( -name '*.cpp' -o -name '*.h' -o -name '*.ui' -o -name '*.html' -o -name '*.txt' -o -name '*.pro' -o -name '*.pri' -o -name '*.ui' -o -name '*.ago' -o -name '*.css' -o -name '*.bwb' -o -name '*.vcproj' \) -exec $UNIX2DOS {} \; &> /tmp/error
+	test -s /tmp/error && more /tmp/error && error "Error while converting newlines to DOS"
+fi
 
 cd ..
 zip -qr $libNameVersion.zip $libNameVersion
@@ -643,12 +655,12 @@ echo "Stop packaging on mac, no rpm or deb created."
 echo "Creating $allTarGZ to update web site"
 tar czf $allTarGZ $libNameVersion.tar.gz $wwwTarGZ $libNameVersion.zip
 echo "scp /tmp/$allTarGZ debunne@www.libqglviewer.com:"
-echo "scp /tmp/$wwwTarGZ debunne@www.libqglviewer.com:"
-
+#echo "scp /tmp/$wwwTarGZ debunne@www.libqglviewer.com:"
+echo ""
 echo "ssh debunne@www.libqglviewer.com"
 echo "tar xzf $allTarGZ"
-echo "tar xzf $wwwTarGZ"
-echo "Copy to /var/www/html/libqglviewer/www"
+echo "cp $libNameVersion.tar.gz $libNameVersion.zip ~/www/src/"
+echo "rm -rf doc && tar xzf $wwwTarGZ && \cp -rf doc/* ~/www"
 exit
 
 echo -n " rpm"
